### ISSUE TITLE
In documentation you miss "setVariablesToRender" tag controller action 

### ISSUE THREAD

**Issue by timruether** [ervaude/json_example#2]
$this->view->setVariablesToRender(['tags']);

you have it only in your github version in abstract controller.
Maybe you can add it to the first steps too.

Thx.

**Comment by ervaude** [comment]
I am sorry. I do not understand what the issue is you are trying to report here.

If you are talking about the blog post: It is only neccessary to set the variableToRender () if you changed the default configuration. This is explained in the section "More complex Objects" (https://usetypo3.com/index.php?id=9#c126).
